### ISSUE TITLE
no files in cocoapods

### ISSUE THREAD

**Issue by nikravi** [enriquez/ECPhoneNumberFormatter#1]
Hello,

I would like to use the library from cocoapods. I installed it, I see the message 
"Using PhoneNumberFormatter (0.1.0)"
but the folder PhoneNumberFormatter is empty. 
Can you check why please? 

Thank you very much

**Comment by enriquez** [comment]
Updated at CocoaPods/Specs@34325f268c6ccaeb8b827b9971e985f6ec302ce8
