### ISSUE TITLE
Crash in stringForObjectValue method on unexpected input on iPad

### ISSUE THREAD

**Issue by JasonNewell** [enriquez/ECPhoneNumberFormatter#2]
This method can't handle non-numeric input. You can force the number pad on the iPhone, but you're stuck with the keyboard (with numbers on top row) on iPad.

Can be fixed by adding this line:

if (unformatted.length == 0) return nil;

directly above

NSString *firstNumber = [unformatted substringToIndex:1],
*output;

in this method

**Comment by jpm** [comment]
I can reproduce the crash, and the fix above worked great. Thanks, Jason!

**Comment by enriquez** [comment]
76d0e5cc6e48b01183e5060867ba3cda6891f3a6
